#####################################
#                                   #
#                                   #
#     Made by xela with love <3     #
#                                   #
#                                   #
#####################################
#put here your message to give to the player on command use (!!!ATTENTION REQUIRES THE discord.use PERMISSION!!!)
messageToPlayer: '&a%player% &7join our server to have notifications on whats going on!'
